#!/usr/bin/python3
import requests
import sys
import json
# this program will be used to gather data on players from the Hypixel minecraft server via command line
# keep in mind I have no affiliation with the Hypixel server
leaderboardoptions = ["UHC", "VAMPIREZ", "SURVIVAL_GAMES", "WALLS3", "QUAKECRAFT", "TNTGAMES", "SUPER_SMASH", "WALLS", "MURDER_MYSTERY", "BUILD_BATTLE", "ARCADE", "GINGERBREAD", "SKYCLASH", "PROTOTYPE", "BEDWARS", "DUELS", "ARENA", "MCGO", "SPEED_UHC", "PAINTBALL", "BATTLEGROUND", "SKYWARS"]
args = []
for arg in sys.argv:
        args.append(str(arg))
i = 0
for command in args:
        if command == "-p":
                alternate = 1
                playerdata = requests.get(
                        url = "https://api.hypixel.net/player", params = {
                                "key": "645d93fe-5a2b-4ade-a1ff-dc1c8d6c4c9a",
                                "name": args[i + 1]}).json()
                optionnum = 0
                viewingdata = playerdata["player"]
                while len(str(viewingdata).split(' ')) > 1:
                        p = 0
                        playeroptions = []
                        for data in viewingdata:
                                print(str(p + 1) + " " + data)
                                p += 1
                                playeroptions.append(data)
                        print("please select what you would like to view")
                        p2 = int(input()) - 1
                        viewingdata = viewingdata[playeroptions[p2]]
                print(viewingdata)
                        
                                
                                
        elif command == "-l":
                leaderboarddata = requests.get(
                        url = "https://api.hypixel.net/leaderboards", params = {
                                "key": "645d93fe-5a2b-4ade-a1ff-dc1c8d6c4c9a"
                        }
                ).json()
                n = 0
                for name in leaderboardoptions:
                     print(str(n + 1) + " " + name)
                     n += 1
                print("please type in the numer that corresponds to the leaderboard you wish to access")
                x = int(input()) - 1
                n = 0
                for option in leaderboarddata["leaderboards"][leaderboardoptions[x - 1]]:
                        print(str(n + 1) + " " + option["title"])
                        n += 1
                print("type in the number for the leaderboard you would like to access")
                y = int(input()) - 1
                u = 0
                leaders = leaderboarddata["leaderboards"][leaderboardoptions[x]][y]["leaders"]
                for uuid in leaders:
                        data = requests.get("https://sessionserver.mojang.com/session/minecraft/profile/" + uuid).json()
                        print(str(u + 1) + " " + data["name"])
                        u += 1
        i += 1


